### PR TITLE
Fix rule filter actions

### PR DESCRIPTION
**Pull request by Arsnael**
Needs https://github.com/apache/james-project/pull/1744

### CODE REVIEW

**Comment by Arsnael** [comment]
Switched to new laptop, might have some schenanigans... not important will check tomorrow

**Comment by Arsnael** [comment]
Ready for review. I put the test that was failing as BasicFeature so that the CI plays it for distributed :)

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.2:buildTar (default) on project scaling-pulsar-smtp: <extraDirectories><paths> contain "from" directory that doesn't exist locally: /home/jenkins/build/workspace/Tmail_build_PR-836/james-project/server/apps/scaling-pulsar-smtp/docker-configuration -> [Help 1]
```
Nice... I feel like I'm gonna enjoy this one...

**Comment by quantranhong1999** [comment]
> Nice... I feel like I'm gonna enjoy this one...

Such a rock falling from the sky :octocat:

**Comment by Arsnael** [comment]
Waiting for this https://github.com/apache/james-project/pull/1747

**Comment by Arsnael** [comment]
Alright now let's see... :D

**Review by chibenwa — APPROVED** [review]

**Pull request merged**
