### PR TITLE
Update James SHA-1 (pg-app)

### PR DESCRIPTION
**Pull request by Arsnael**
Rebase on james/postgresql branch for tmail pg app

### CODE REVIEW

**Review by quantranhong1999 — APPROVED** [review]

**Comment by vttranlina** [comment]
CI failed:
```
webSocketShouldPushNewMessageWhenChangeSubscriptionOfMailbox(GuiceJamesServer) – com.linagora.tmail.james.MemoryMailboxSetMethodTest

Expecting actual:
  "{"@type":"Response","requestId":"req-36","sessionState":"2c9f1b12-b35a-43e6-9af2-0106fb53a943","methodResponses":[["Mailbox/set",{"accountId":"29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6","oldState":"770d5c82-9649-4708-bdf2-4f9f27925a6f","updated":{"1":{}},"newState":"ca21a801-c929-40fc-91e9-4660bbe6cf9a"},"c1"]]}"
to start with:
  "{"@type":"StateChange","changed":{"29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6":{"Mailbox":"
```

It looks like related to commit: https://github.com/apache/james-project/pull/2108/files#diff-ac1365541e08f69dc4e57ee445faa58e904eb86a908f3b76c359ace9b0aa376f

image

**Comment by Arsnael** [comment]
Yes it is, was looking into it :) Escaped me...

@hungphan227 can you explain me again why that change initially? Did you check it was not affecting other tests than postgres?

**Comment by hungphan227** [comment]
> Yes it is, was looking into it :) Escaped me...
> 
> @hungphan227 can you explain me again why that change initially? Did you check it was not affecting other tests than postgres?

Oh sorry I have not checked MemoryMailboxSetMethodTest

**Comment by Arsnael** [comment]
Why does it comes second for postgres and not other implems though? :)

**Comment by Arsnael** [comment]
Disabling that test temporarily for now. That should be fixed on base James.

**Comment by Arsnael** [comment]
=> https://github.com/linagora/james-project/issues/5133

**Review by vttranlina — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Review by hungphan227 — APPROVED** [review]

**Pull request merged**
