### PR TITLE
Distributed app: default config to relax mailbox name validation

### PR DESCRIPTION
**Pull request by quantranhong1999**

### CODE REVIEW

**Review by Arsnael — COMMENTED** [review]
Do we really need to enable it by default on tmail?

**Comment by quantranhong1999** [comment]
> Do we really need to enable it by default on tmail?

Answered in: https://github.com/linagora/tmail-backend/pull/1174#issuecomment-2333758581

But this could just be optional for the ticket though.

It is weird that `DistributedImapAndSmtpTest` failed on CI on both PRs with opensearch container failed startup error.
I just tested locally and it is fine...

**Comment by Arsnael** [comment]
I saw the opensearch been failing regularly to start lately on tmail-backend... Also seems we use an image for those depoyment tests that's a bit outdated (2.1.0). Can we match the one used in james? Maybe the image is more stable? (hard gamble here I'm not really convinced but...)

**Comment by quantranhong1999** [comment]
> Can we match the one used in james? Maybe the newer image is more stable?

https://github.com/linagora/tmail-backend/pull/1176

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
