### PR TITLE
ISSUE-895 [Postgres] TMail pg-app - TODO remain 

### PR DESCRIPTION
**Pull request by vttranlina**
resolve https://github.com/linagora/tmail-backend/issues/895

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Review by hungphan227 — APPROVED** [review]

**Comment by Arsnael** [comment]
https://james-jenkins.lin-saas.com/job/Tmail%20build/job/PR-899/7/testReport/com.linagora.tmail.deployment/PostgresImapAndSmtpTest/validateDeployment/

Second time in a row I see this deployment test failing, usually when like this it  means it's real.

@vttranlina can you check? :)

**Comment by vttranlina** [comment]
I'm investigating it, It looks like related to DeleteMessageListener in James.

**Comment by vttranlina** [comment]
Wait for the PR fix bug merged, then we can update the new SHA on this PR

https://github.com/linagora/james-project/issues/5044

**Review by Arsnael — APPROVED** [review]

**Comment by vttranlina** [comment]
green

**Pull request merged**
