### PR TITLE
Update James project SHA1

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Review by quantranhong1999 — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-cli) on project memory-jmap-integration-tests: There was a timeout or other error in the fork -> [Help 1]
```
Been 3 times in a row I get this... It's odd but suspicious... Will investigate

**Comment by Arsnael** [comment]
Can reproduce locally with the mvn command line... it's really weird. Will try to dig more...

**Comment by Arsnael** [comment]
> The diff between them is JAMES-3715 commits. Could be a clue?

Likely... Smells :D

**Comment by chibenwa** [comment]
See  https://github.com/linagora/tmail-backend/pull/396

**Pull request closed without merging**
