### PR TITLE
ISSUE-245 Have a MailboxAppender recognizing team mailboxes

### PR DESCRIPTION
**Pull request by Arsnael**
Likely many wrong things atm, WIP

### CODE REVIEW

**Comment by Arsnael** [comment]
Before the last commit it was working. In the last commit I tried to make the code more functional reactive and... well it's not great yet

**Comment by Arsnael** [comment]
I still have to make a TmailLocalDelivery  class

**Comment by vttranlina** [comment]
> Just need to wait for the one in apache james to be green

you can resolve conflict while waiting time :v

**Comment by Arsnael** [comment]
```
[ERROR] shouldUseMemoryMailboxManager{GuiceJamesServer}  Time elapsed: 0.181 s  <<< ERROR!

com.github.fge.lambdas.ThrownByLambdaException: org.apache.commons.configuration2.ex.ConfigurationException: Unable to init mailet TmailLocalDelivery

Caused by: org.apache.commons.configuration2.ex.ConfigurationException: Unable to init mailet TmailLocalDelivery

Caused by: javax.mail.MessagingException: Can not load mailet TmailLocalDelivery

Caused by: java.lang.ClassNotFoundException: TmailLocalDelivery
```
Likely missed to add the maven packages there (and every module where I put that TmailLocalDelivery mailet)... will fix that

**Pull request merged**
