### PR TITLE
[BACKPORT] JAMES-3963 Full text search: AND for combining phrase terms

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
Can rebase on James, Apache PR has been merged

**Comment by quantranhong1999** [comment]
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.6.1:testCompile (scala-test-compile) on project tmail-mailets: Execution scala-test-compile of goal net.alchim31.maven:scala-maven-plugin:4.6.1:testCompile failed: Compilation failed: InterfaceCompileFailed -> [Help 1]

**Comment by Arsnael** [comment]
Hm... correct me if I'm wrong but when I see the code around Redis changes, did you try to apply changes of James submodule latest master with forgetting updating James SHA-1 first perhaps?

**Review by quantranhong1999 — APPROVED** [review]

**Review by Arsnael — COMMENTED** [review]
Still a draft or not?

**Comment by chibenwa** [comment]
No, no longer a draft

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
