### PR TITLE
Update James SHA-1

### PR DESCRIPTION
**Pull request by vttranlina**
Manually resolve of https://github.com/linagora/tmail-backend/pull/1270

### CODE REVIEW

**Comment by vttranlina** [comment]
The team mailboxes test failed
`listTeamMailboxesByDomainShouldReturnStoredEntriesWhenSingle – com.linagora.tmail.team.TeamMailboxRepositoryTest`

- The reson is the changed of method [StoreMailboxManager#getBaseMailboxes](https://github.com/apache/james-project/blob/85f69b363e05e8757ff5d6a82dbd4bac289045d3/mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java#L845)
- James commit: [316522363b679d53fb2cc9e7b1561f6d75f2414e](https://github.com/apache/james-project/commit/316522363b679d53fb2cc9e7b1561f6d75f2414e#diff-78bbaf3505920ad8d1c2dfb95f2cbc4de2ed01c358645ad50e9b531483e3c25a)

With query input
-  MailboxQuery = MailboxQuery.builder
    .namespace(TEAM_MAILBOX_NAMESPACE)
    .matchesAllMailboxNames
    .build`

it alway return `Flux.empty` 

I'm not sure about this logic, can you look it? @chibenwa 
```java
private Flux<Mailbox> getBaseMailboxes(MailboxMapper mailboxMapper,MailboxQuery mailboxQuery, MailboxSession session) {
        if (mailboxQuery.isPrivateMailboxes(session)
          || mailboxQuery.getNamespace().isEmpty() && mailboxQuery.getUser().isEmpty()) {
            return mailboxMapper.findMailboxWithPathLike(toSingleUserQuery(mailboxQuery, session));
        } else {
            return Flux.empty();
        }
    }
```

**Comment by vttranlina** [comment]
> @vttranlina where is `listTeamMailboxesByDomain` used?

webadmin:
TeamMailboxManagementRoutes

**Comment by chibenwa** [comment]
>webadmin:
> TeamMailboxManagementRoutes

Then F... that.

getBaseMailboxes is inttended to return only mailboxes belonging to the user. If it was not the case and pieces of code relied on a non compliant behaviour then it was a mistake.

Here if the intent is to list team mailboxes `mailboxManager.list(...).filter(...)` would IMO 100% do the job and not trying to abuse mailboxManager.search(...) sounds like a good idea.

**Comment by vttranlina** [comment]
Another failed

```
Location: /org/apache/james/imap/scripts/ValidateDeployment.test:114
LastClientMsg: A001 NAMESPACE
Expected: '\* NAMESPACE \(\((\"\"|\"#private\.\") \".\"\)\) NIL NIL'
Actual   : '* NAMESPACE (("" ".")) (("#user." ".")) NIL'
```
`org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation#validateDeployment`

**Comment by vttranlina** [comment]
requirement: 
- https://github.com/apache/james-project/pull/2484

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
I guess good for reupdating james-sha1 with the needed change?

**Review by quantranhong1999 — APPROVED** [review]

**Pull request merged**
