### PR TITLE
Upgrade James-SHA1

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[ERROR] Tests run: 114, Failures: 0, Errors: 1, Skipped: 4, Time elapsed: 152.09 s <<< FAILURE! - in org.apache.james.mailbox.elasticsearch.ElasticSearchIntegrationTest
[ERROR] searchShouldReturnCorrectResultWhenByMessageId  Time elapsed: 1.219 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.util.function.Function.apply(Object)" because the return value of "java.util.Map.get(Object)" is null
```
I have clearly other issues locally but I'm working on it...

**Comment by Arsnael** [comment]
```
[ERROR] validateDeployment  Time elapsed: 63.349 s  <<< ERROR!
org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 

Location: /org/apache/james/imap/scripts/ValidateDeployment.test:24
LastClientMsg: 10 CREATE appendexpunge
Expected: '10 OK CREATE completed.'
Actual   : '10 OK [MAILBOXID (86ff6190-7451-11ed-b2d5-656151569329)] CREATE completed.'

[ERROR] selectThenFetchWithExistingMessages  Time elapsed: 60.666 s  <<< ERROR!
org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 

Location: /org/apache/james/imap/scripts/SelectThenFetchWithExistingMessages.test:24
LastClientMsg: A02 CREATE selectTest
Expected: 'A02 OK CREATE completed\.'
Actual   : 'A02 OK [MAILBOXID (d0e169c0-7451-11ed-a63a-0dcf5f5f9859)] CREATE completed.'
```

**Comment by quantranhong1999** [comment]
Let's adapt this: https://github.com/apache/james-project/commit/02a1240b597e21e5a3a66aab77f3ef073811ca7e

**Comment by Arsnael** [comment]
> Let's adapt this: [apache/james-project@02a1240](https://github.com/apache/james-project/commit/02a1240b597e21e5a3a66aab77f3ef073811ca7e)

I know :) was working on the fix, here: https://github.com/apache/james-project/pull/1346

**Review by chibenwa — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Pull request merged**
