### PR TITLE
apache/james-project update to master branch

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
```
[ERROR] Errors: 
[ERROR]   EncryptedMemoryServerTest.shouldEncryptContent:126 » ConditionTimeout Conditio...
[ERROR]   MemoryServerTest.mailsContentWithUnicodeCharactersShouldBeKeptUnChanged » ConditionTimeout
[ERROR]   MemoryServerTest.mailsShouldBeWellReceivedByBothRecipient » ConditionTimeout A...
[ERROR]   MemoryServerTest.mailsShouldBeWellReceivedByTenRecipient » ConditionTimeout As...
[ERROR]   MemoryServerTest.mailsShouldBeWellReceived » ConditionTimeout Assertion condit...
[ERROR]   MemoryServerTest.oneHundredMailsShouldBeWellReceived » ConditionTimeout Assert...
```
I restarted the build but those issues popped in the two previous builds so we might have a problem

**Comment by Arsnael** [comment]
Same. There is probably an issue. I might take a look later if you don't

**Comment by chibenwa** [comment]
Yes, please...

**Comment by Arsnael** [comment]
I can reproduce locally, confirm the issue. Will try to investigate

**Comment by Arsnael** [comment]
Should work :)

**Comment by Arsnael** [comment]
```
[ERROR] selectThenFetchWithExistingMessages  Time elapsed: 55.938 s  <<< ERROR!
org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 

Location: /org/apache/james/imap/scripts/SelectThenFetchWithExistingMessages.test:21
LastClientMsg: A01 LOGIN imapuser@domain password
Expected: 'A01 OK LOGIN completed\.'
Actual   : 'A01 NO LOGIN failed. Plain login / authentication are disabled.'
```

**Review by chibenwa — COMMENTED** [review]
:+1:

**Comment by Arsnael** [comment]
Squashed, was green

**Comment by chibenwa** [comment]
Huge thanks rene

**Pull request merged**
