### PR TITLE
ISSUE-624 New tag for Linagora apisix image

### PR DESCRIPTION
**Pull request by Arsnael**
Pushed `linagora/apisix:3.2.0-debian-sentinel-javaplugin` to the linagora docker repo already

### CODE REVIEW

**Review by vttranlina — COMMENTED** [review]
The new tag can make confuse (at least to me) that the image only supports "sentinel"

**Comment by Arsnael** [comment]
What do you propose then? Can't be the same tag or all current env might get broken

**Comment by Arsnael** [comment]
@vttranlina How about `linagora/apisix:3.2.0.1-debian-javaplugin` then for example?

**Comment by vttranlina** [comment]
> @vttranlina How about `linagora/apisix:3.2.0.1-debian-javaplugin` then for example?

What do you think of `linagora/apisix:3.2.0-debian-javaplugin-0.2`? We should retain` xxxapisix:3.2.0-xxx` as the placeholder for the apisix version.

**Comment by Arsnael** [comment]
Fine with this, thanks :)

**Comment by Arsnael** [comment]
@vttranlina done!

**Review by quantranhong1999 — APPROVED** [review]

**Pull request merged**
