### PR TITLE
[NO_MERGE] [FOR CI TEST] Rebase postgres on master 

### PR DESCRIPTION
**Pull request by vttranlina**
Continue of https://github.com/linagora/tmail-backend/pull/1302

### CODE REVIEW

**Review by hungphan227 — APPROVED** [review]

**Comment by Arsnael** [comment]
LGTM, good job.

Shall we push this then on postgresql branch?

**Comment by hungphan227** [comment]
Missing PostgresPublicAssetRepositoryTest. IMO should add in another PR.

**Comment by hungphan227** [comment]
> LGTM, good job.
> 
> Shall we push this then on postgresql branch?

Yes

**Comment by vttranlina** [comment]
> Missing PostgresPublicAssetRepositoryTest. IMO should add in another PR.

Missing what? can you explain more?

I see it already exists `tmail-backend/jmap/extensions-postgres/src/test/java/com/linagora/tmail/james/jmap/publicAsset/PostgresPublicAssetRepositoryTest.java` 
image

**Comment by Arsnael** [comment]
Pushed to postgresql branch.

@hungphan227 and @vttranlina thanks for the hard work on this!

**Pull request closed without merging**
