### PR TITLE
ISSUE-441 Migrate OpenSearch 2.0.0 for TMail

### PR DESCRIPTION
**Pull request by quantranhong1999**
Work left:
- Fix failing tests if there are
- Remove open distro tests module
- Replace OpenDistro docker extension with OpenSearch 2.0.0 in tests and docker-compose
- Documentation where appropriate

### CODE REVIEW

**Comment by Arsnael** [comment]
You should rebase on this instead, I think it's still on the old pr : https://github.com/apache/james-project/pull/1061

I'm not sure about the cc_sort workaround btw... As the fix has been merged on the client but still no release... I'm afraid we forget about it and it stays... And also normally it means you have to do that workaround on other fields as well... 

Not sure I want to apply it TBH, but I can't make a decision really...

**Comment by quantranhong1999** [comment]
> You should rebase on this instead, I think it's still on the old pr : https://github.com/apache/james-project/pull/1061

Already point James to this PR.

> And also normally it means you have to do that workaround on other fields as well...

What do you mean other fields? At least on the TMail side, I do not see a similar failed test related to auto-complete feature.

**Comment by Arsnael** [comment]
We don't have tests covering other fields but in a running env, if you do a sort on a field on mails that have this to null, likely gonna fail... like for cc (could image bcc, and maybe others)

As I said though in my latest PR I did not put for now the cc_sort build trick, so unnecessary here IMO for now (but just be on standby for now)

**Comment by Arsnael** [comment]
This work can be rebased on master regarding the split decided in two steps high level rest client and then new java client.

The PR on apache james : https://github.com/apache/james-project/pull/1061

**Comment by quantranhong1999** [comment]
> This work can be rebased on master regarding the split decided in two steps high level rest client and then new java client.

Maybe we should wait for the new java client on James is merge and then rebase? If rebase on TMail master now it is likely non-sense cause it needs the new client dependency on James's side.

**Comment by chibenwa** [comment]
Needs a rebase?

**Comment by quantranhong1999** [comment]
> Needs a rebase?

Not really. This is already rebased on the waiting-to-be merged work on James (https://github.com/apache/james-project/pull/1061)

**Comment by chibenwa** [comment]
Needs a rebase...

**Comment by vttranlina** [comment]
I rebased & migrated new code in another pr: 
https://github.com/linagora/tmail-backend/pull/544

**Pull request closed without merging**
