### PR TITLE
ISSUE-833 Audit trail

### PR DESCRIPTION
**Pull request by vttranlina**
resolve https://github.com/linagora/tmail-backend/issues/833

### CODE REVIEW

**Comment by vttranlina** [comment]
TODO: Should wait to pr https://github.com/apache/james-project/pull/1747 merged, then Update james sha1

**Comment by Arsnael** [comment]
It is merged :)

**Comment by vttranlina** [comment]
> It is merged :)

I see it is still open, it is pulsar package pr, not audit trail pr

**Comment by Arsnael** [comment]
Ah sorry ^^

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
