### PR TITLE
[OIDC] Demo with OIDC (lemon) set up and TeamMail flutter web frontend

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
Reopen of https://github.com/linagora/tmail-backend/pull/617

**Comment by Arsnael** [comment]
Weird... it doesn't work locally for me.

I did start with the dev.sh bash script, I did add the line in my hosts file... but the SSO doesn't work

I don't get the SSO page of tmailweb, I get the normal one. Normally if I'm not wrong, tmail-web asks for the webfinger endpoint in the backend, then he gets the SSO endpoint to it? I don't even see the webfinger call being made on my local...

I will try to dig into it but it's weird

**Comment by chibenwa** [comment]
> Normally if I'm not wrong, tmail-web asks for the webfinger endpoint in the backend, then he gets the SSO endpoint to it? 

Yes

**Comment by Arsnael** [comment]
@chibenwa I think been a while you are working on this... can you try pulling up the latest tmail-web master image, redeploy your docker compose and clear your browser cache as well before reloading tmail-web? I suspect a regression!

I get the webfinger request for example with prior tmail-web version (0.7.1, 0.7.5), but master branch, there is no request to webfinger at all for me

**Comment by chibenwa** [comment]
@Arsnael can you open an issue to the mobile team ?

Do not forget the to add the `regression` tag.

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-flutter/issues/1670

**Comment by chibenwa** [comment]
https://user-images.githubusercontent.com/6928740/228198161-1b1dd144-27d3-4e3f-be1a-3b5f89779d93.mp4

**Comment by Arsnael** [comment]
Working for you again? I'm confused

**Comment by chibenwa** [comment]
using v0.7.5

**Comment by Arsnael** [comment]
0.7.5 yes works, 0.7.6 for me too :)

**Comment by tk-nguyen** [comment]
FYI, I cannot reproduce this with the master image.

https://user-images.githubusercontent.com/39090621/228212112-07d234f3-0d88-4034-8dd1-4e7e4b8a9922.mp4

**Comment by Arsnael** [comment]
I cannot reproduce it today either... It works fine now :o I honestly don't know what happened u_u

**Comment by quantranhong1999** [comment]
FYI, the demo (both SSO, SLO) works for me with latest `tmail-backend` and `tmail-web` image from dockerhub.

**Comment by chibenwa** [comment]
7todo too: set up a domain...

**Comment by Arsnael** [comment]
> 7todo too: set up a domain...

noticed you can't send an email without it yes :) let me take a look at it

**Comment by quantranhong1999** [comment]
I pushed an LSC commit to Benoit' branch: https://github.com/linagora/tmail-backend/pull/619/commits/7795b74bafa885ce2e609b9f08f3dcb9d37aa7b6

Result:
demo-domain-contact
demo-identity

**Comment by Arsnael** [comment]
Ok changed the domain to tmail.com, it works as showed in the following video:

[oidc-tmail-lemonldap.webm](https://user-images.githubusercontent.com/9005025/228455012-ce8e5a7c-0b5b-4895-8419-c188d6ea702d.webm)

I forgot the SLO but the behavior stays the same...

I added as well a pull command before starting the containers as I had countless issues before finally noticing my tmail-backend memory image was 10 months old... could maybe explain the issues I had yesterday too. 

With forcing a pull though, no problem.

**Comment by Arsnael** [comment]
Rebased and squash fixup

When it's green, is it good to merge @chibenwa ?

**Comment by chibenwa** [comment]
> When it's green, is it good to merge @chibenwa ?

Of course

**Pull request merged**
