### PR TITLE
Upgrade james version to 3.9.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by Arsnael**
Missed that one with upgrade to latest SHA-1...

### CODE REVIEW

**Review by quantranhong1999 — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
Needed for other projects?

**Comment by Arsnael** [comment]
Talking about the customer ones? Depends no?

**Comment by quantranhong1999** [comment]
```

[ERROR] Failures: 

[ERROR]   MemoryMailboxGetMethodTest.stateShouldTakeIntoAccountDelegationWhenCapability 1 expectation failed.

JSON path methodResponses[0][1].state doesn't match.

Expected: not "2c9f1b12-b35a-43e6-9af2-0106fb53a943"

  Actual: 2c9f1b12-b35a-43e6-9af2-0106fb53a943



[ERROR]   MemoryMailboxSetMethodTest.lookupRightShouldBePropagated JSON documents are different:

Different keys found in node "methodResponses[1][1].list[0].rights", missing: "methodResponses[1][1].list[0].rights.andre@domain.tld", expected: <{"andre@domain.tld":[l]}> but was: <{}>



[ERROR]   MemoryMailboxSetMethodTest.oldStateShouldIncludeSetChanges JSON documents are different:

Array "methodResponses[1][1].updated" has different length, expected: <1> but was: <0>.

Array "methodResponses[1][1].updated" has different content. Missing values: ["1"], extra values: [], expected: <["1"]> but was: <[]>



[ERROR]   MemoryMailboxSetMethodTest.stateShouldTakeIntoAccountDelegationWhenCapability 1 expectation failed.

JSON path methodResponses[0][1].oldState doesn't match.

Expected: not "2c9f1b12-b35a-43e6-9af2-0106fb53a943"

  Actual: 2c9f1b12-b35a-43e6-9af2-0106fb53a943



[ERROR]   MemoryMailboxSetMethodTest.webSocketShouldPushNewMessageWhenChangeSubscriptionOfMailbox 

Expecting actual:

  "{"@type":"Response","requestId":"req-36","sessionState":"2c9f1b12-b35a-43e6-9af2-0106fb53a943","methodResponses":[["Mailbox/set",{"accountId":"29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6","oldState":"2c9f1b12-b35a-43e6-9af2-0106fb53a943","updated":{"1":{}},"newState":"2c9f1b12-b35a-43e6-9af2-0106fb53a943"},"c1"]]}"

to start with:

  "{"@type":"StateChange","changed":{"29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6":{"Mailbox":"
```

**Comment by Arsnael** [comment]
Yep saw it and investigating it :)

**Comment by Arsnael** [comment]
Seems something wrong with states and/or delegation?

**Comment by vttranlina** [comment]
I re-upgrade SHA + upgrade version to 3.9.0-SNAPSHOT + fix ci error at https://github.com/linagora/tmail-backend/pull/695

**Comment by Arsnael** [comment]
Thanks I lacked time last friday to work on it :)

**Pull request closed without merging**
