### PR TITLE
ISSUE-1095 More @BasicFeature JMAP integration tests

### PR DESCRIPTION
**Pull request by vttranlina**
resolve https://github.com/linagora/tmail-backend/issues/1095

### CODE REVIEW

**Review by quantranhong1999 — COMMENTED** [review]
+1 for `TeamMailboxSmtpContract` too IMO.

**Comment by p-tungtv-nissho** [comment]
> TeamMailboxSmtpContract

it did
https://github.com/linagora/tmail-backend/blob/master/tmail-backend/integration-tests/smtp/distributed-smtp-integration-tests/src/test/java/com/linagora/tmail/james/DistributedTeamMailboxSmtpTest.java#L24

**Comment by vttranlina** [comment]
> +1 for `TeamMailboxSmtpContract` too IMO.

it did
https://github.com/linagora/tmail-backend/blob/master/tmail-backend/integration-tests/smtp/distributed-smtp-integration-tests/src/test/java/com/linagora/tmail/james/DistributedTeamMailboxSmtpTest.java#L24

**Review by quantranhong1999 — APPROVED** [review]

**Comment by chibenwa** [comment]
+1 overall.

Can we get build time before and after for information?

**Comment by vttranlina** [comment]
> Can we get build time before and after for information?

**Before**: `Team-mail :: Integration Tests :: JMAP :: Distributed SUCCESS [05:10 min]`
Using the result of pr:  https://github.com/linagora/tmail-backend/pull/1092
Ci result: https://james-jenkins.lin-saas.com/blue/organizations/jenkins/Tmail%20build/detail/PR-1092/1/pipeline/

**After**: `Team-mail :: Integration Tests :: JMAP :: Distributed SUCCESS [37:03 min]`
Using the result of this pr
CI result: https://james-jenkins.lin-saas.com/blue/organizations/jenkins/Tmail%20build/detail/PR-1096/3/pipeline/

Note that both pr run in same CI runner: ci-james-06
The gap is ~ 30 minutes, it's quite longer than my local test (3 minutes for all BasicFeature tag)
image

**Comment by vttranlina** [comment]
After reuse forks:
`Team-mail :: Integration Tests :: JMAP :: Distributed SUCCESS [05:57 min]` 
It looks good

**Review by quantranhong1999 — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]
Perfect thanks

**Comment by vttranlina** [comment]
squash fixup

**Review by hungphan227 — APPROVED** [review]

**Pull request merged**
