### PR TITLE
[JRE] Adopt JRE 20

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
Screenshot from 2023-04-03 13-10-05

Plenty good enough.

Ps: it sounds like @Arsnael found and solved our preprod issue :-p

**Comment by Arsnael** [comment]
Timeout three times in a row for deployment-tests-distributed ... I think there is a wolf here

**Comment by chibenwa** [comment]
```
07:15:37.574 [ERROR] 🐳 [linagora/tmail-backend-distributed:latest] - Log output from the failed container:
[0.023s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.025s][error  ][gc,task  ] Failed to create worker thread
```

Related. Need debug.

On preprod this is running fine...

**Comment by chibenwa** [comment]
> 10k

I mean better than master :-) Similar to the MIME4J enhancements...

For the build failure that is weird...

Screenshot from 2023-04-03 15-36-32

Runs perfectly locally...

**Comment by Arsnael** [comment]
I mean you managed to run perf tests so I don't doubt it as well... Something odd going on

**Comment by chibenwa** [comment]
```
mvn test --pl :deployment-tests-distributed

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.linagora.tmail.deployment.DistributedJmapTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 132.802 s - in com.linagora.tmail.deployment.DistributedJmapTest
[INFO] Running com.linagora.tmail.deployment.DistributedCliTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 56.021 s - in com.linagora.tmail.deployment.DistributedCliTest
[INFO] Running com.linagora.tmail.deployment.DistributedImapAndSmtpTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 191.875 s - in com.linagora.tmail.deployment.DistributedImapAndSmtpTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:30 min (Wall Clock)
[INFO] Finished at: 2023-04-04T09:57:03+07:00
[INFO] ------------------------------------------------------------------------
```

My bate: outdated docker version / ubuntu version...

**Comment by Arsnael** [comment]
> My bate: on the CI outdated docker version / ubuntu version...
> 
> @Arsnael could you try update those?

Hmmm not a bad bet. The workers for tmail-backend builds are on the old VMs where I can't install latest docker version because the debian used is too old and I'm afraid that a dist upgrade would bring more problems than it would solve...

But now that we don't need to manage the tmail-web build, I could try to swap those workers in the newer VMs where I updated Docker. Will have a look when I have time.

**Comment by Arsnael** [comment]
Been doing changes on the CI and relaunched the build... let's see the result :)

**Comment by Arsnael** [comment]
Still same issue... Might take a look myself when i have time

**Comment by Arsnael** [comment]
The build seems going on ok now... let's wait and see.

What I changed: well I checked again docker versions differences between newly rebuilt worker and VM...
- VM was still 23.0.1 from the last time I updated
- worker was 23.0.3... 

And after upgrading the version in the VM to 23.0.3 it seems ok. If on newer docker versions now even a small minor version gap is enough to put chaos... aouch!

I will really look into forcing docker versions in our workers, depending on our VMs, I think it's the best to do here.

**Comment by chibenwa** [comment]
Thanks @Arsnael for the good job on this!

:green_apple:  build!

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
