### PR TITLE
Upgrade James SHA-1

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
Need this to be merged first: https://github.com/apache/james-project/pull/1496

**Comment by Arsnael** [comment]
Rebase with latest james. Hope it's green now

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-cli) on project memory-deployment-tests: There was a timeout or other error in the fork -> [Help 1]
```
3 times in a row... need to investigate, even if it's very cryptic

**Comment by Arsnael** [comment]
Found the culprit...

MemoryJmapTest.sessionRouteAndUploadRouteAndDownloadRouteShouldWork

It's hanging forever, and when looking at the james logs inside the container, we have this:

```
09:42:03.338 [WARN ] r.c.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:                                                         [109/1934]
java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpHeaderValidationUtil
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 46 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaderValidationUtil
        at org.apache.james.jmap.routes.DownloadRoutes.sanitizeHeaderValue(DownloadRoutes.scala:330)
        at org.apache.james.jmap.routes.DownloadRoutes.$anonfun$downloadBlob$2(DownloadRoutes.scala:316)
        at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:85)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
        at reactor.core.publisher.MonoIgnorePublisher.subscribe(MonoIgnorePublisher.java:57)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
        at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:156)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
        at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545) 
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) 
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:146)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:156)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74)
        at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

The issue is only present in memory tmail deployment test

**Comment by Arsnael** [comment]
> Look at netty jars on the class path.
> 
> Mvn dependency tree to audit where the mismatch come from.
> 
> My bet: testing dependencies

I did... firebase-admin 9.1.0... it forces the netty-codec-http to 4.1.82 as it's not defined anywhere else in the memory deps.

Your bet is wrong :) 

Distributed includes blob-s3 that declares specifically this dep with the aligned version, likely why it's not mismatching.

I'm trying a bunch of stuff to do appropriate change

**Comment by Arsnael** [comment]
Waiting for https://github.com/apache/james-project/pull/1499 to be merged

I prefer declaring all the netty libs used directly in the master pom, so all james and project like ours inheriting james can benefit of that alignment.

If I add the netty-codec-http manually in the memory app pom, the problem is as it's not declared in james pom, you need to add a version... then we would need to constantly keep it up to date with james one... which is a pain :) So I prefer the above solution

**Comment by Arsnael** [comment]
Rebased on latest james master... come on give me that green :D

**Review by vttranlina — APPROVED** [review]

**Review by quantranhong1999 — APPROVED** [review]

**Pull request merged**
