### PR TITLE
Update James SHA-1

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by vttranlina** [comment]
the pr https://github.com/linagora/tmail-backend/pull/774 also update james sha-1 and tried to adapt something

**Comment by quantranhong1999** [comment]
> Would expect a better follow up of your works in this matter :)

CI: `FileNotFoundException: redis`
IMO either loosely check on the Redis configuration file existence (see my other PR), or just add RedisExtension to all ITs.

**Comment by vttranlina** [comment]
> I just think of the release we gonna have to do soon

will the release `0.7.1-rc1` contain the new jmap quota? I thought yes, So IMO we should update Sha after jmap quota is done on james

**Comment by chibenwa** [comment]
We should be able to start without the Redis file

**Pull request closed without merging**
