### PR TITLE
Upgrade JDK to 21

### PR DESCRIPTION
**Pull request by quantranhong1999**
Let's see the `jdk17` CI node complains first...

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project testing-base: Fatal error compiling: error: release version 21 not supported -> [Help 1]
```
:)

**Comment by vttranlina** [comment]
Do we need to change jdk21 to postgresql branch?

**Comment by Arsnael** [comment]
The next rebase on master after it is changed on apache james as well for postgres. Let's not rush things for now please

**Comment by Arsnael** [comment]
Mockito issues, cf Benoit's PR on upgrade jdk21 for apache james, I remember seeing fixes for it

**Comment by quantranhong1999** [comment]
> Mockito issues, cf Benoit's PR on upgrade jdk21 for apache james, I remember seeing fixes for it

Yes. TMail Java 21 needs to update some dependencies on the James side. Likely we should migrate James to Java 21 first.

I am trying some quick wins to build the TMail part now.

**Comment by Arsnael** [comment]
Yes I think we dont have a choice than updating Apache James :)

**Review by chibenwa — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

**Review by Arsnael — CHANGES_REQUESTED** [review]
Blocking just for the time the upgrade on James side is merged, as some dependencies have been manually upgraded here in james submodule.

Owerthise looks ok :)

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
