### PR TITLE
Change blob store module chooser

### PR DESCRIPTION
**Pull request by chibenwa**
We were always encrypting the blob even if we are not saving it because of single-save

Cc @vttranlina 

Note: guice injection are fucked up, I ended up reverting and not doing it for CNB as it was non essential

### CODE REVIEW

**Comment by Arsnael** [comment]
```
1) [Guice/MissingImplementation]: No implementation for BlobStoreDAO annotated with @Named("wrapped") was bound.
```

**Comment by vttranlina** [comment]
Read it,
honestly, I do not understand this pr, I see the pr just changing the name of guice instance
`unencrypted` -> `wrapped`

**Comment by chibenwa** [comment]
@Arsnael will explain you.

We should lookup for singleSave then encrypt.
Not the reverse.

**Comment by Arsnael** [comment]
@chibenwa I'm sorry, joining @vttranlina side here, I'm not sure I fully get what's going on in this PR either

**Comment by chibenwa** [comment]
The PR changes are likely bullshit.

> We should lookup for singleSave then encrypt. Not the reverse.

That's the important bit.

**Comment by vttranlina** [comment]
rework pr https://github.com/linagora/tmail-backend/pull/930

**Pull request closed without merging**
